import {v4} from 'uuid'

const books = [
    {
      title: 'Book 1',
      author: 'Author 1',
      publisher: 'Publisher 1',
      category: 'Category 1',
      description: 'Description 1',
      retailPrice: 10.99,
      isbn: 'ISBN-1',
      image:'https://picsum.photos/200/30',
      book_id:v4(),

    },
    {
      title: 'Book 2',
      author: 'Author 2',
      publisher: 'Publisher 2',
      category: 'Category 2',
      description: 'Description 2',
      retailPrice: 12.99,
      isbn: 'ISBN-2',
      image:'https://picsum.photos/200/50',
      book_id:v4(),
    },
    {
      title: 'Book 3',
      author: 'Author 3',
      publisher: 'Publisher 3',
      category: 'Category 3',
      description: 'Description 3',
      retailPrice: 8.99,
      isbn: 'ISBN-3',
      image:'https://picsum.photos/50/300',
      book_id:v4(),
    },
    {
      title: 'Book 4',
      author: 'Author 4',
      publisher: 'Publisher 4',
      category: 'Category 1',
      description: 'Description 4',
      retailPrice: 14.99,
      isbn: 'ISBN-4',
      image:'https://picsum.photos/100/100',
      book_id:v4(),
    },
    {
      title: 'Book 5',
      author: 'Author 5',
      publisher: 'Publisher 5',
      category: 'Category 2',
      description: 'Description 5',
      retailPrice: 9.99,
      isbn: 'ISBN-5',
      image:'https://picsum.photos/300/300',
      book_id:v4(),
    },
    {
      title: 'Book 6',
      author: 'Author 6',
      publisher: 'Publisher 6',
      category: 'Category 3',
      description: 'Description 6',
      retailPrice: 11.99,
      isbn: 'ISBN-6',
      image:'https://picsum.photos/200/400',
      book_id:v4(),
    },
    {
      title: 'Book 7',
      author: 'Author 7',
      publisher: 'Publisher 7',
      category: 'Category 1',
      description: 'Description 7',
      retailPrice: 7.99,
      isbn: 'ISBN-7',
      image:'https://picsum.photos/400/300',
      book_id:v4(),
    },
    {
      title: 'Book 8',
      author: 'Author 8',
      publisher: 'Publisher 8',
      category: 'Category 2',
      description: 'Description 8',
      retailPrice: 13.99,
      isbn: 'ISBN-8',
      image:'https://picsum.photos/200/100',
      book_id:v4(),
    },
    {
      title: 'Book 9',
      author: 'Author 9',
      publisher: 'Publisher 9',
      category: 'Category 3',
      description: 'Description 9',
      retailPrice: 15.99,
      isbn: 'ISBN-9',
      image:'https://picsum.photos/200/200',
      book_id:v4(),
    },
    {
      title: 'Book 10',
      author: 'Author 10',
      publisher: 'Publisher 10',
      category: 'Category 1',
      description: 'Description 10',
      retailPrice: 10.49,
      isbn: 'ISBN-10',
      image:'https://picsum.photos/100/300',
      book_id:v4(),
    },
  ];
  
  export default books;
  