import { v4 } from 'uuid';
import img from './img.jpg';

const books = [
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    publisher: 'Scribner',
    category: 'Classic Literature',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 10.99,
    isbn: 'ISBN-1',
    image: img,
    book_id: v4(),
    viewed: 100,
    rating: 4.5,
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publisher: 'J. B. Lippincott & Co.',
    category: 'Classic Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 12.99,
    isbn: 'ISBN-2',
    image: img,
    book_id: v4(),
    viewed: 150,
    rating: 4.2,
  },
  {
    title: '1984',
    author: 'George Orwell',
    publisher: 'Secker & Warburg',
    category: 'Dystopian Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 8.99,
    isbn: 'ISBN-3',
    image: img,
    book_id: v4(),
    viewed: 200,
    rating: 4.8,
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publisher: 'T. Egerton, Whitehall',
    category: 'Classic Romance',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 14.99,
    isbn: 'ISBN-4',
    image: img,
    book_id: v4(),
    viewed: 120,
    rating: 4.6,
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J. D. Salinger',
    publisher: 'Little, Brown and Company',
    category: 'Coming-of-Age Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 9.99,
    isbn: 'ISBN-5',
    image: img,
    book_id: v4(),
    viewed: 80,
    rating: 4.1,
  },
  {
    title: 'To the Lighthouse',
    author: 'Virginia Woolf',
    publisher: 'The Hogarth Press',
    category: 'Modernist Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 11.99,
    isbn: 'ISBN-6',
    image: img,
    book_id: v4(),
    viewed: 90,
    rating: 4.4,
  },
  {
    title: 'Moby-Dick',
    author: 'Herman Melville',
    publisher: 'Harper & Brothers',
    category: 'Adventure Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 7.99,
    isbn: 'ISBN-7',
    image: img,
    book_id: v4(),
    viewed: 60,
    rating: 4.3,
  },
  {
    title: 'The Lord of the Rings',
    author: 'J. R. R. Tolkien',
    publisher: 'George Allen & Unwin',
    category: 'Fantasy Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 13.99,
    isbn: 'ISBN-8',
    image: img,
    book_id: v4(),
    viewed: 170,
    rating: 4.7,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    publisher: 'Smith, Elder & Co.',
    category: 'Gothic Fiction',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 15.99,
    isbn: 'ISBN-9',
    image: img,
    book_id: v4(),
    viewed: 110,
    rating: 4.0,
  },
  {
    title: 'The Hobbit',
    author: 'J. R. R. Tolkien',
    publisher: 'George Allen & Unwin',
    category: 'Children\'s Fantasy',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla id rhoncus elit, eu efficitur risus.',
    retailPrice: 10.49,
    isbn: 'ISBN-10',
    image: img,
    book_id: v4(),
    viewed: 130,
    rating: 4.9,
  },
];

export default books;
